# Generated by Django 2.2.6 on 2019-10-25 18:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.IntegerField(default=0)),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True, default=0, verbose_name='Wzrost')),
                ('date_of_birth', models.DateField(blank=True, verbose_name='Data urodzenia')),
                ('sex', models.CharField(choices=[('M', 'mężczyzna'), ('F', 'kobieta')], max_length=1, null=True,
                                         verbose_name='płeć')),
                ('chart_js_code', models.TextField(null=True)),
                ('goal_weight',
                 models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)],
                                   verbose_name='')),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight',
                 models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)],
                                   verbose_name='Masa ciała')),
                ('bf_percent', models.FloatField(blank=True, null=True,
                                                 validators=[django.core.validators.MinValueValidator(0),
                                                             django.core.validators.MaxValueValidator(100)],
                                                 verbose_name='Procent tkanki tłuszczowej')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements',
                                              to='panel.Profile')),
            ],
        ),
    ]
